{
  "uid" : "d72178f6ea778e",
  "name" : "test_new_article_from_file",
  "fullName" : "test_conduit.test_all_conduit.TestConduit1#test_new_article_from_file",
  "historyId" : "118977acd433c20dfae392836695407f",
  "time" : {
    "start" : 1628284369486,
    "stop" : 1628284376783,
    "duration" : 7297
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: '../article.csv'",
  "statusTrace" : "self = <test_all_conduit.TestConduit1 object at 0x7f1dd73d3340>\n\n    def test_new_article_from_file(self):\n        #conduit_registration(self.driver)\n        conduit_signin(self.driver)\n        time.sleep(2)\n        self.driver.find_element_by_xpath('//*[@class=\"nav navbar-nav pull-xs-right\"]//li[4]/a').click()\n        time.sleep(3)\n        sajat_cikk2 = self.driver.find_elements_by_xpath('//*[@id=\"app\"]//a/h1')\n        cikkek_szama=len(sajat_cikk2)\n        self.driver.implicitly_wait(4)\n>       with open('../article.csv', 'r', encoding=\"utf-8\") as csv_in:  # mit nyitunk meg, milyen változó néveel\nE       FileNotFoundError: [Errno 2] No such file or directory: '../article.csv'\n\ntest_conduit/test_all_conduit.py:143: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: '../article.csv'",
    "statusTrace" : "self = <test_all_conduit.TestConduit1 object at 0x7f1dd73d3340>\n\n    def test_new_article_from_file(self):\n        #conduit_registration(self.driver)\n        conduit_signin(self.driver)\n        time.sleep(2)\n        self.driver.find_element_by_xpath('//*[@class=\"nav navbar-nav pull-xs-right\"]//li[4]/a').click()\n        time.sleep(3)\n        sajat_cikk2 = self.driver.find_elements_by_xpath('//*[@id=\"app\"]//a/h1')\n        cikkek_szama=len(sajat_cikk2)\n        self.driver.implicitly_wait(4)\n>       with open('../article.csv', 'r', encoding=\"utf-8\") as csv_in:  # mit nyitunk meg, milyen változó néveel\nE       FileNotFoundError: [Errno 2] No such file or directory: '../article.csv'\n\ntest_conduit/test_all_conduit.py:143: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "9e1315e041068d31",
      "name" : "log",
      "source" : "9e1315e041068d31.txt",
      "type" : "text/plain",
      "size" : 344
    }, {
      "uid" : "99c205f9b7b70653",
      "name" : "stderr",
      "source" : "99c205f9b7b70653.txt",
      "type" : "text/plain",
      "size" : 215
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test_conduit"
  }, {
    "name" : "suite",
    "value" : "test_all_conduit"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit1"
  }, {
    "name" : "host",
    "value" : "fv-az47-991"
  }, {
    "name" : "thread",
    "value" : "3713-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_conduit.test_all_conduit"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "d72178f6ea778e.json",
  "parameterValues" : [ ]
}